Cliente/Cliente/Controllers/SectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.Models;
using Cliente.Comunication;

namespace Cliente.Controllers
{
    public class SectorsController : Controller
    {
    

        public async Task<IActionResult> Index()
        {
            var sectors = await SectorComm.GetSectors();
            foreach(var item in sectors)
            {
                item.Stadium = await StadiumComm.GetStadium(item.StadiumId);
            }
            return View(sectors);
        }

        public async Task<IActionResult> Details(int id)
        {
            var sector = await SectorComm.GetSector(id);
            sector.Stadium = await StadiumComm.GetStadium(sector.StadiumId);
            if (sector == null)
            {
                return NotFound();
            }

            return View(sector);
        }

        public async Task<IActionResult> Create()
        {
            ViewData["StadiumId"] = new SelectList(await StadiumComm.GetStadiums(), "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Colunas,Linhas,StadiumId")] Sector sector)
        {
            if (ModelState.IsValid)
            {
                var created = SectorComm.PostSector(sector);
                if(created != null)
                    return RedirectToAction(nameof(Index));
            }
            ViewData["StadiumId"] = new SelectList(await StadiumComm.GetStadiums(), "Id", "Name", sector.StadiumId);
            return View(sector);
        }
        public async Task<IActionResult> Edit(int id)
        {
            var sector = await SectorComm.GetSector(id);
            if (sector == null)
            {
                return NotFound();
            }
            ViewData["StadiumId"] = new SelectList(await StadiumComm.GetStadiums(), "Id", "Name", sector.StadiumId);
            return View(sector);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Colunas,Linhas,StadiumId")] Sector sector)
        {
            if (id != sector.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await SectorComm.PutSector(id, sector);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (SectorComm.GetSector(id)==null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StadiumId"] = new SelectList(await StadiumComm.GetStadiums(), "Id", "Name", sector.StadiumId);
            return View(sector);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var sector = await SectorComm.GetSector(id);
            if (sector == null)
            {
                return NotFound();
            }

            return View(sector);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sector = await SectorComm.DeleteSector(id);
            if(sector == true)
                return RedirectToAction(nameof(Index));
            return View(sector);
        }
    }
}

Cliente/Cliente/Controllers/StadiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.Models;
using Cliente.Comunication;

namespace Cliente.Controllers
{
    public class StadiaController : Controller
    {

        public async Task<IActionResult> Index()
        {
            return View(await StadiumComm.GetStadiums());
        }

        public async Task<IActionResult> Details(int id)
        {
            var stadium = await StadiumComm.GetStadium(id);
            if (stadium == null)
            {
                return NotFound();
            }

            return View(stadium);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Stadium stadium)
        {
            if (ModelState.IsValid)
            {
                var stadiumCreated = await StadiumComm.PostStadium(stadium);
                if(stadiumCreated != null)
                return RedirectToAction(nameof(Index));
            }
            return View(stadium);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var stadium = await StadiumComm.GetStadium(id);
            if (stadium == null)
            {
                return NotFound();
            }
            return View(stadium);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Stadium stadium)
        {
            if (id != stadium.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await StadiumComm.PutStadium(id,stadium);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (StadiumComm.GetStadium(stadium.Id)==null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(stadium);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var stadium = await StadiumComm.GetStadium(id);
            if (stadium == null)
            {
                return NotFound();
            }

            return View(stadium);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stadium = await StadiumComm.DeleteStadium(id);
            if(stadium == true)
                return RedirectToAction(nameof(Index));
            return View(stadium);
        }
    }
}

Cliente/Cliente/Views/Stadia/Create.cshtml
@model Cliente.Models.Stadium

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Stadium</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Cliente/Cliente/Views/Stadia/Delete.cshtml
@model Cliente.Models.Stadium

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Stadium</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Cliente/Cliente/Views/Stadia/Details.cshtml
@model Cliente.Models.Stadium

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Stadium</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dt>
    </dl>
</div>
<a asp-controller="Sectors" asp-action="Create">New Sector</a>
<h4>Sectors</h4>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Linhas</th>
            <th>Colunas</th>
            <th>Capacidade</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Sectors)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Linhas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Colunas)
            </td>
            <td>
                @Html.DisplayFor(modelItem =>item.Capacidade)
                
            </td>
            <td>
                <a asp-controller="Sectors" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-controller="Sectors" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-controller="Sectors" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Cliente/Cliente/Views/Stadia/Edit.cshtml
@model Cliente.Models.Stadium

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Stadium</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Cliente/Cliente/Views/Stadia/Index.cshtml
@model IEnumerable<Cliente.Models.Stadium>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>