Cliente/Cliente/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Cliente.Models
{
    public class Login
    {
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

Cliente/Cliente/Controllers/LoginController.cs
using Cliente.Comunication;
using Cliente.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Cliente.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        public LoginController(ILogger<LoginController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            return View();
        }
 

        public IActionResult Login()
        {
            return View();
        }


        public async Task<IActionResult> Authentication([Bind("Username,Password")] Login @user)
        {
            try
            {
                if (user == null || string.IsNullOrEmpty(user.Password) || string.IsNullOrEmpty(user.Username))
                    return View("Login");

                ClaimsIdentity identity = null;
                UserLogin tk = null;
                if ((tk = await LoginComm.Authentication(user)) != null)
                {
                    identity = new ClaimsIdentity(new[]
                    {
                        new Claim(ClaimTypes.Name,tk.User.Name),
                        new Claim(ClaimTypes.Role,tk.User.Role.ToString()),
                        new Claim(ClaimTypes.Rsa,tk.Token),
                    }, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(identity));
                    return RedirectToAction("Index");
                }
                else return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Cliente/Cliente/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Cliente.Models;
using Cliente.Comunication;

namespace Cliente.Controllers
{
    public class UsersController : Controller
    {


        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await UserComm.GetUsers());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var user = await UserComm.GetUser(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Username,Password,Contact,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                var aux = await UserComm.PostUser(user);
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        public async Task<IActionResult> Edit(int id)
        {

            var user = await UserComm.GetUser(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Username,Password,Contact,Role")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var edited =  await UserComm.PutUser(id,user);
                    if (edited == true)
                        return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (UserComm.GetUser(user.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(user);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var user = await UserComm.GetUser(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await UserComm.DeleteUser(id);
            if(user == true)
                return RedirectToAction(nameof(Index));
            return NotFound();
        }
    }
}

Cliente/Cliente/Views/Login/Index.cshtml
@{
}

<fieldset>
    <legend>User DashBoard</legend>
    <fieldset class="fHorizontalCenter">
        <label style="font-size:18px">Welcome </label>
        <label> 
        @if (User.Identity.IsAuthenticated) 
        { 
            @User.Identity.Name; 
        }
        </label><br/>
    </fieldset>
</fieldset>

    

Cliente/Cliente/Views/Login/Login.cshtml
@model Cliente.Models.Login

@{ViewData["Title"] = "Login";}


<div class="row">
    <div class="col-md-4">
        <form asp-controller="Login" asp-action="Authentication">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Username</label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Password</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-success" />
                <a asp-controller="Users" asp-action="Create" class="btn btn-primary">Registar</a>
            </div>
        </form>
    </div>
</div>